#ifndef TESTROBOTAGENT_GLOBAL_H
#define TESTROBOTAGENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTROBOTAGENT_LIBRARY)
#  define TESTROBOTAGENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTROBOTAGENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTROBOTAGENT_GLOBAL_H
